version: '3.7'

services: 
  
  nginx:
    env_file: ./.env
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    image: nginx
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: 
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes: 
      - ./www:/var/www
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/config/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/config/mime.types:/etc/nginx/mime.types
      - ./logs/nginx:/var/log/nginx
    depends_on: 
      - ${PHP_FPM_CONTAINER_NAME}
      - ${DB_CONTAINER_NAME}
    networks:
      - network
  
  mysql:
    env_file: ./.env 
    image: "mysql:${DB_VERSION}"
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports: 
      - "${DB_PORT}:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_NAME: ${DB_CONTAINER_NAME}
      SERVICE_TAGS: ${APP_ENV}
    volumes:
      - ./dbdata/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

    networks: 
      - network
  
  php:
    env_file: ./.env 
    build:
      args:
        user: ${APP_USER_NAME}
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    container_name: ${PHP_FPM_CONTAINER_NAME}
    volumes: 
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_FPM_PORT}:9000"
    environment:
      - SERVICE_NAME=${PHP_FPM_CONTAINER_NAME}
      - SERVICE_TAGS=${APP_ENV}
    networks: 
      - network

  phpmyadmin:
    env_file: ./.env
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_FPM_CONTAINER_NAME}
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - ${DB_CONTAINER_NAME}
    networks:
      - network

networks: 
  network:
    driver: bridge