version: '3'

networks: 
  lempnet:

services: 
  
  nginx:
    env_file: ./.env
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    image: nginx
    container_name: nginx
    restart: always
    stdin_open: true
    tty: true
    ports: 
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes: 
      - ./www:/var/www
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on: 
      - php
      - mysql
    networks:
      - lempnet
  
  mysql:
    env_file: ./.env 
    image: "mysql:${DB_VERSION}"
    container_name: mysql
    restart: always
    tty: true
    stdin_open: true
    ports: 
      - "${DB_PORT}:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    volumes:
      - ./dbdata/mysql/:/var/lib/mysql/
    networks: 
      - lempnet
  
  php:
    env_file: ./.env 
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_FPM_PORT}:9000"
    networks: 
      - lempnet

  phpmyadmin:
    env_file: ./.env
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
    restart: always    
    depends_on:
      - mysql
    networks:
      - lempnet